# Generated by Django 5.1.2 on 2024-11-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_limite', models.DateField()),
                ('ordem_apresentacao', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
