# Generated by Django 5.1.2 on 2024-11-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
