# Generated by Django 5.1.2 on 2024-11-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tarefas_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_limite', models.DateField()),
                ('ordem_apresentacao', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tarefas',
        ),
    ]
